/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "cloud-20210518220832-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://dytlt0venc1ki.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:1aadccb9-f7c1-492e-96aa-941639b65c0b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_uQDzNL7fo",
    "aws_user_pools_web_client_id": "6cip4fvegouuecuqqgr7v0l0pb",
    "oauth": {}
};


export default awsmobile;
